### ISSUE TITLE
error on generation if you don't npm run generate first

### ISSUE THREAD

**Issue by peterwillis** [DavidWells/react-proptype-autocomplete#2]
After I cloned, instead of generating the react-toolbox completions, I went straight for material-ui that I had elsewhere. This was the output:

```
node generate-completions.js --src ~/Projects/test/node_modules/material-ui/**/*.js
React Doc Gen Finished. Build Tokens
fs.js:585
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/name/.atom/packages/react-proptype-autocomplete/react-doc-gen-output.json'
    at Error (native)
    at Object.fs.openSync (fs.js:585:18)
    at Object.fs.readFileSync (fs.js:432:33)
    at generateCompletions (/Users/name/.atom/packages/react-proptype-autocomplete/parse-docgen.js:11:33)
    at /Users/name/.atom/packages/react-proptype-autocomplete/generate-completions.js:19:3
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at maybeClose (internal/child_process.js:819:16)
    at Socket.<anonymous> (internal/child_process.js:320:11)
```

If I ran npm run generate first, and then run as above, it seems to work ok.

**Comment by DavidWells** [comment]
This was fixed in the atom plugin. See details on the setup here http://davidwells.io/autocomplete-for-react-component-proptypes/
