### ISSUE TITLE
Failed to activate the atom-react-autocomplete package

### ISSUE THREAD

**Issue by hstoebel** [DavidWells/react-proptype-autocomplete#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-react-autocomplete](https://github.com/DavidWells/atom-react-autocomplete) package, v0.1.10
### Stack Trace

Failed to activate the atom-react-autocomplete package

```
At Cannot read property 'path' of null

TypeError: Cannot read property 'path' of null
    at currentFilePath (/Users/stoebelj/.atom/packages/atom-react-autocomplete/lib/getCurrentPath.js:7:58)
    at Object.module.exports.loadCompletions (/Users/stoebelj/.atom/packages/atom-react-autocomplete/lib/provider.js:309:15)
    at Object.module.exports.activate (/Users/stoebelj/.atom/packages/atom-react-autocomplete/lib/main.js:8:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:760:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-react-autocomplete, v0.1.10 (inactive)
atom-react-native-autocomplete, v0.0.27 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
erb-snippets, v1.1.0 (inactive)
git-diff-details, v1.3.0 (inactive)
highlight-selected, v0.11.2 (inactive)
language-javascript-jsx, v0.3.7 (inactive)
react, v0.15.0 (inactive)
remote-atom, v1.3.9 (inactive)
split-diff, v1.0.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by igorbarbashin** [comment]
Had the same issue. Saw `Cannot read property 'path' of null` after initial restart and then seems the package hasn't been activated.
`completion.json` looks correct. But the react-autocomplete doesn't show the suggestions

**Comment by SanthoshDhandapani** [comment]
Could someone provide the completion json?

**Comment by scutuyu** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [atom-react-autocomplete](https://github.com/DavidWells/atom-react-autocomplete) package 0.1.10


### Stack Trace

Failed to activate the atom-react-autocomplete package

```
At Cannot read property 'path' of null

TypeError: Cannot read property 'path' of null
    at currentFilePath (/packages/atom-react-autocomplete/lib/getCurrentPath.js:7:58)
    at Object.loadCompletions (/packages/atom-react-autocomplete/lib/provider.js:309:15)
    at Object.activate (/packages/atom-react-autocomplete/lib/main.js:8:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:846:34
```

### Commands

```
  2x -4:53.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
emmet-atom-plugin 0.0.1 
atom-react-autocomplete 0.1.10 
autocomplete-js-import 1.4.0 
language-javascript-jsx 0.3.7 
```

what should I do?

**Comment by craigscript** [comment]
I'm also facing this issue, can anyone help?

**Comment by edi** [comment]
Same here :)

**Comment by googol7** [comment]
Same here

**Comment by TheJayWright** [comment]
Just started for me randomly today after the weekend.

**Comment by DavidWells** [comment]
Hey everyone. I no longer have time to maintain this project. Is anyone interested in becoming a core contributor and fixing some of these issues?

**Comment by ChrisRast** [comment]
@DavidWells Hello, create an issue and update the readme so people will be able to see it easily. It will help gather volunteers. :)
I unfortunately do not have time to help, sorry…
